### ISSUE TITLE
data.csv should be data.parquet

### ISSUE THREAD

**Issue by phormio** [aws-samples/aws-glue-jobs-unit-testing#10]
Please consider the first and last lines of [this block](https://github.com/aws-samples/aws-glue-jobs-unit-testing/blob/62a3016162ccd6b2d2badf4c2805d21f407b70fd/tests/test_sample.py#L11-L59) to see why `data.csv` on the first line of the block should be `data.parquet`.

**Comment by praveenflash** [comment]
Fixed the name.
