### ISSUE TITLE
Not able to mock aws glue module

### ISSUE THREAD

**Issue by vsrinivaskanuparthi** [aws-samples/aws-glue-jobs-unit-testing#11]
I have an glue python script which uses boto3 services (dynamodb, s3, ssm other services). i have written an pytest test case and trying to import an function from the main glue script and want to test it. i am getting below error

from awsglue.utils import getResolvedOptions
E   ModuleNotFoundError: No module named 'awsglue'

import pytest
from unittest.mock import patch, MagicMock
from module import transform_epac_tdu_description

def test_transform_epac_tdu_description():
    # Test case 1: Normal description with various patterns
    input_description = 'This is a test description with newline\\ncharacters and\\u0000some \\r special "characters" and &nbsp; HTML tags <p>test</p>.'
    expected_output = 'This is a test description with various patterns and some special characters and HTML tags test.'
    assert transform_epac_tdu_description(input_description) == expected_output
    
    how to tackle this issue how to not get error for awsglue module. how to mock it or how to avoid it.

**Comment by praveenflash** [comment]
Try the Moto package for mocking the awsglue libraries.

**Comment by vsrinivaskanuparthi** [comment]
i have tried its not working.

from awsglue.utils import getResolvedOptions

args = getResolvedOptions(sys.argv, ['JOB_NAME','parameter_name'])

can you give me an example how to mock above lines using moto

**Comment by praveenflash** [comment]
Here is a sample test case

```python
import unittest
import sys
from unittest import mock


class TestMyApp(unittest.TestCase):

    def test_mock_stubs(self):
        mocked_awsglue = mock.MagicMock()
        sys.modules['awsglue.utils'] = mocked_awsglue
        mocked_awsglue.getResolvedOptions.return_value = {}

        # move the import here to make sure that the mocks are setup before it's imported
        import my_app
```
