### ISSUE TITLE
COMMAND_EXECUTION_ERROR Message

### ISSUE THREAD

**Issue by Overlord1997** [aws-samples/aws-glue-jobs-unit-testing#4]
Hi Team,

I'm getting this error during the build phase - 

"Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: python3 -m pytest tests/ --junitxml=$CODEBUILD_SRC_DIR/$JUNIT_XML. Reason: exit status 5".

Regards,
Garvit Tiwari

**Comment by Overlord1997** [comment]
Hi Team,

Above issue is fixed. 

I have a query -- How can I multiple deployment of glue jobs with different scripts from same pipeline and assign them different Job names?

**Comment by praveenflash** [comment]
You can use the cloudformation template to deploy more glue jobs with different names.

**Comment by Overlord1997** [comment]
Hi Praveen, 

Thanks for your reply, that will definitely work for 2-5 Glue Jobs. 

But what I'm trying to achieve is deploying 50+ Glue Jobs that to not time dependent. Once a developer finishes his/her code they will push the code to the repo and then we need to deploy it. And the new deployment should not affect the older deployments unless there is a change in the Native script.

**Comment by praveenflash** [comment]
You can use terraform and perform this operation.

**Comment by Overlord1997** [comment]
I know I'm asking a lot, but can you share some reference DOC for the same?
