### ISSUE TITLE
DOCS: README.md - ap-southeast-3 mentioned twice

### ISSUE THREAD

**Issue by samjeffrees** [aws-samples/aws-glue-jobs-unit-testing#5]
Towards the top of the readme I can see the following sentence:

> The AWS Cloudformation template provided in this sample does not work in **ap-southeast-3**, af-south-1, ap-northeast-3, **ap-southeast-3**, me-south-1 and us-gov-east-1 AWS regions due to service limitations.

ap-southeast-3 is mentioned twice. is one of these mentions maybe supposed to be ap-southeast-1 or ap-southeast-2?

**Comment by praveenflash** [comment]
Yes, it is meant for ap-southeast-1
