### ISSUE TITLE
Can we also use moto server to mock calls for catalogue operations?

### ISSUE THREAD

**Issue by tmottershead** [aws-samples/aws-glue-jobs-unit-testing#8]
Thanks for a really useful resource. I have tried it and it works well.  I have used the ThreadedMotoServer to good effect:
```
MOTO_IPADDR = "127.0.0.1"
MOTO_PORT = 5000
MOTO_ENDPOINT = f"http://{MOTO_IPADDR}:{MOTO_PORT}"

@pytest.fixture(scope="session", name="moto_server")
def moto_fixture():
    from moto.server import ThreadedMotoServer
    server = ThreadedMotoServer(MOTO_IPADDR, MOTO_PORT, True)
    server.start()
    yield server
    server.stop()
```
Are you able to add further examples where AWS Glue Catalogue calls from Spark APIs are handled by moto server?  It would be good if we can unit test PySpark code such as:

```
DataFrameWriter
  .write
  .format("parquet")
  .mode("append" or "overwrite")
  .partitionBy(<partition_fields>)
  .saveAsTable(name=f"{db_name}.{table_name}", path=tbl_s3_path)
```
`SparkSession.sql(f'CREATE DATABASE {db_name} LOCATION {s3_uri}')`

I have tried testing code similiar to the above examples by setting `core-site.xml` spark config property:
```
<property>
    <name>aws.glue.endpoint</name>
    <value>http://127.0.0.1:5000</value>
</property>
``` 

but am getting errors of the form:

```
pyspark.sql.utils.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: 
MetaException(message:Got exception: org.apache.hadoop.fs.s3a.UnknownStoreException `s3://test-prep-bucket/spark_parquet_unit_test/unit_test': 
getFileStatus on s3://test-prep-bucket/spark_parquet_unit_test/unit_test: 
com.amazonaws.services.s3.model.AmazonS3Exception:  (Service: Amazon S3; Status Code: 404; Error Code: 
NoSuchBucket; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null:
NoSuchBucket:  (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: null; S3 Extended Request ID: null; Proxy: null))
```
Perhaps there are other related spark/hadoop/hive config settings which also need to be updated so that we can point catalogue related calls to moto.  Do you know if it is possible to intercept calls from Spark API calls using moto server for glue?

**Comment by praveenflash** [comment]
I haven't tried that before. Will let you know if I can successfully test it.
